### ISSUE TITLE
Can't export

### ISSUE THREAD

**Issue by coolpringles** [HeathLoganCampbell/MinecraftBut#1]
Whenever I try to export it (using the latest version of eclipse) it says this:

> JAR creation failed. See details for additional information.
  Class files on classpath not found or not accessible for: 'MinecraftBut/src/main/java/games/bevs/minecraftbut/MinecraftButPlugin.java'
  Class files on classpath not found or not accessible for: 'MinecraftBut/src/main/java/games/bevs/minecraftbut/commands/MinecraftButCommand.java'
  Class files on classpath not found or not accessible for: 'MinecraftBut/src/main/java/games/bevs/minecraftbut/commons/Console.java'
  Class files on classpath not found or not accessible for: 'MinecraftBut/src/main/java/games/bevs/minecraftbut/commons/gui/MenuIcon.java'
  Class files on classpath not found or not accessible for: 'MinecraftBut/src/main/java/games/bevs/minecraftbut/commons/gui/Menu.java'
  Class files on classpath not found or not accessible for: 'MinecraftBut/src/main/java/games/bevs/minecraftbut/commons/utils/CC.java'
  Class files on classpath not found or not accessible for: 'MinecraftBut/src/main/java/games/bevs/minecraftbut/commons/utils/Callback.java'
  Class files on classpath not found or not accessible for: 'MinecraftBut/src/main/java/games/bevs/minecraftbut/commons/utils/ItemStackBuilder.java'
  Class files on classpath not found or not accessible for: 'MinecraftBut/src/main/java/games/bevs/minecraftbut/commons/utils/MathUtils.java'
  Class files on classpath not found or not accessible for: 'MinecraftBut/src/main/java/games/bevs/minecraftbut/gui/SenerarioMenu.java'
  Class files on classpath not found or not accessible for: 'MinecraftBut/src/main/java/games/bevs/minecraftbut/senerario/ScenerarioManager.java'
  Class files on classpath not found or not accessible for: 'MinecraftBut/src/main/java/games/bevs/minecraftbut/senerario/Senerario.java'
  Class files on classpath not found or not accessible for: 'MinecraftBut/src/main/java/games/bevs/minecraftbut/senerario/senerarios/OneHit.java'
  Class files on classpath not found or not accessible for: 'MinecraftBut/src/main/java/games/bevs/minecraftbut/senerario/senerarios/TheLavaRises.java'
  Class files on classpath not found or not accessible for: 'MinecraftBut/src/main/java/games/bevs/minecraftbut/senerario/senerarios/TheWaterRises.java'
  Class files on classpath not found or not accessible for: 'MinecraftBut/src/main/java/games/bevs/minecraftbut/senerario/senerarios/NoJump.java'
  Class files on classpath not found or not accessible for: 'MinecraftBut/src/main/java/games/bevs/minecraftbut/senerario/senerarios/RainingBlocks.java'
  Class files on classpath not found or not accessible for: 'MinecraftBut/src/main/java/games/bevs/minecraftbut/senerario/senerarios/TNTRain.java'
  Class files on classpath not found or not accessible for: 'MinecraftBut/src/main/java/games/bevs/minecraftbut/senerario/senerarios/EnderDragonAppears.java'
  Class files on classpath not found or not accessible for: 'MinecraftBut/src/main/java/games/bevs/minecraftbut/world/ButWorld.java'

How do I export it? Or can you provide a jar?
Thanks.

**Comment by HeathLoganCampbell** [comment]
Oh sure, I'll add a jar

**Comment by HeathLoganCampbell** [comment]
Here you go man
[The jar](https://github.com/HeathLoganCampbell/MinecraftBut/releases/tag/1.1)
