### ISSUE TITLE
World Decay

### ISSUE THREAD

**Issue by Zynfernus** [HeathLoganCampbell/MinecraftBut#10]
Hello, I recently used your plugin, everything worked smoothly and I love this plugin! However, there was an issue about the command for decaysPerSecond. For instance when I enter "/mb s WorldDecay decaysPerSecond 100", an error message pops up and says "Something went wrong, incorrect type? int? true|false?" I watched skeppy's video and double checked the command was correct. I am running it on 1.8 server, and I don't understand what's wrong, can you please help me? I will insert a reference photo.
<img width="1280" alt="Screen Shot 2019-10-26 at 11 30 49 AM" src="https://user-images.githubusercontent.com/57025643/67613792-1517db80-f7e4-11e9-83af-246383b54424.png">

**Comment by HeathLoganCampbell** [comment]
Oh yeah, that was a bug I patch a bit ago but never released a jar, I'll do that for you now

**Comment by HeathLoganCampbell** [comment]
Here you go, try this version
https://github.com/HeathLoganCampbell/MinecraftBut/releases/tag/1.5
