### ISSUE TITLE
World Border

### ISSUE THREAD

**Issue by Zynfernus** [HeathLoganCampbell/MinecraftBut#11]
Is there a way to extend the border but also have the scenarios working in the extended places? Thank you.

**Comment by HeathLoganCampbell** [comment]
Yeah, of course just use the default minecraft worldborder command, warning tho, the larger the border the more you'll lag with such scenarios as lava is rising.

Example
```/worldborder add 100```
to increase the border by 100 blocks

**Comment by Zynfernus** [comment]
I did the border add command but the scenarios doesnt work there, like for example the world decay only decays the blocks in the original border, not outside

**Comment by HeathLoganCampbell** [comment]
I'll add a command to allow the border to be extended sometime within the next 2 weeks then (Currently I have exams and I'm ill, So I can't do much right now)

**Comment by CyberFlameGO** [comment]
Have you tried to reload the server after setting a new worldborder? That may work
