### ISSUE TITLE
Built .jar Not Included

### ISSUE THREAD

**Issue by eternalUnion** [HeathLoganCampbell/MinecraftBut#12]
I have been trying to put the project on eclipse and create a .jar file, but cannot find dependencies. Can you add .jar file to the project so it is easier to install?

**Comment by HeathLoganCampbell** [comment]
Are you adding it in eclipse as a maven project? because you shouldn't need any jars to install this plugin?

**Comment by eternalUnion** [comment]
No i tried to add it as a java project. Can you tell me how can i do that?

**Comment by HeathLoganCampbell** [comment]
import > Existing Maven projects > browse to the folder of "Minecraftbut"
I'll also assume you haven't ran spigot's buildtools, so you'll need to run that as well for 1.8.8
then you'll need lombok which you just download and run to install on your eclipse

I would suggest watching a few videos on maven, it's a tool that a lot of java developers use daily

OH! and to compile the jar, right click on the project, go to run, then maven build [as seen here](https://gyazo.com/2b275080b838e169efc8cc865d0fdf13) which will build it to "target/Minecraftbut.jar"

helpful resources
- https://bukkit.org/threads/tutorial-setting-up-maven.204521/
- https://www.spigotmc.org/wiki/buildtools/#1-8-8
- https://projectlombok.org/download

**Comment by eternalUnion** [comment]
Thanks for the support. I'm using Linux and having problems with installing lombok so I'll switch to Windows. As soon as i get the jar file I am going to close the issue

**Comment by HeathLoganCampbell** [comment]
I'll try make a youtube video sometime in the next few weeks going over how to set this plugin up because it does seem over complicated if you have never used these tools before

**Comment by eternalUnion** [comment]
I imported the project, set up lombok (also included .jar in buildpath) and ran buildtools (in a directory, didn't know where to add in the project). Eclipse gives errors like "Missing artifact", "Failed to read artifact descriptor" and "The container 'Maven Dependencies' reference non existing library". What should I do?

**Comment by eternalUnion** [comment]
.jar created (issue closed)
