### ISSUE TITLE
Rising Water Not Working

### ISSUE THREAD

**Issue by JayBFC** [HeathLoganCampbell/MinecraftBut#13]
**Describe the bug**
Basically, in chat, it says "the water has risen", but none of the water within the border actually rises. I don't see any errors in the server console.

**To Reproduce**
1. Enable water rising
2. Stand near any water within the border
3. Wait until it says "the water has risen"

**Expected behavior**
I expected the water level to have risen by one block.

**Desktop (please complete the following information):**
 - Server Version: 1.8
 - Server Type: Spigot

**Additional context**
This is not specifically to do with the water rising, but pretty much every mode in MinecraftBut works perfectly fine, apart from the ones to do with water rising (haven't tested the lava).

**Comment by HeathLoganCampbell** [comment]
I'll look into it now, thank you :)

**Comment by HeathLoganCampbell** [comment]
Could you please add me on discord? Heath#5377
