### ISSUE TITLE
Linked Inventories is Missing

### ISSUE THREAD

**Issue by SuperPotatoGod** [HeathLoganCampbell/MinecraftBut#16]
**Describe the bug**
Linked Inventories does not appear in the scenerio selector.

**To Reproduce**
1. Do /mb

**Expected behavior**
To have access to Linked Inventories

**Desktop (please complete the following information):**
 - Server Version: 1.14.4
 - Server Type: Paper

**Comment by BIurple** [comment]
problem is the .java file which is used for the scenario is missing, I think it is supposed to be called "LinkedInventories.java" and it isn't appearing in the source code when I download it

MinecraftBut-1.7 > src > main > java > games > bevs > minecraftbut > senerario > senerarios .

that is where the scenarios are located, and Linkedinventories.java isn't there, hope the owner notices!

**Comment by HeathLoganCampbell** [comment]
oh? It is here [LinkedInventories](https://github.com/HeathLoganCampbell/MinecraftBut/blob/master/src/main/java/games/bevs/minecraftbut/senerario/senerarios/linkedinvs/LinkedInventories.java) but it's only supported for 1.8
