### ISSUE TITLE
Linked inventories

### ISSUE THREAD

**Issue by BIurple** [HeathLoganCampbell/MinecraftBut#19]
**Describe the bug**
Linked Inventories not showing up on selection of scenarios.

**To Reproduce**
1. Go to 'a local minecraft server (spigot/paper/bukkit)'
2. Put 'minecraftbut' in plugins
3. go in server and type '/mb'
4. Linked inventories doesn't show up

**Expected behavior**
Linked inventories to show up in scenarios.

**Screenshots**
Screenshot added of LinkedInventories not showing up in source code
https://user-images.githubusercontent.com/59361052/71579354-a1f95100-2b15-11ea-9f07-446c8b2fd6d9.png
.

**Desktop (please complete the following information):**
 - Server Version: 1.14.4
 - Server Type: Spigot

**Additional context**
LinkedInventories.java doesn't show up in source code from what I've seen.

**Comment by HeathLoganCampbell** [comment]
Linked inventories is only supported in 1.8, I believe
