### ISSUE TITLE
Lava comes down instead of going up

### ISSUE THREAD

**Issue by coolpringles** [HeathLoganCampbell/MinecraftBut#2]
When I turned on the lava rising situation, it came down from the top instead of rising from the bottom. Also I'm playing on 1.8.8 if that helps.

**Comment by HeathLoganCampbell** [comment]
Sorry, it was set high for the second video
Try  something along the lines of
```
/MinecraftBut Senerario TheLavaRises LavaStartLevel 8
```

**Comment by coolpringles** [comment]
Thanks, I think it worked!
