### ISSUE TITLE
No Linked Inventories?

### ISSUE THREAD

**Issue by MaxieDF** [HeathLoganCampbell/MinecraftBut#20]
I installed the newest version with no luck on the linked inventories feature. it does not show up

**Comment by HeathLoganCampbell** [comment]
Are you on 1.8?

**Comment by CyberFlameGO** [comment]
Noticed that this is their first issue. @ImpulsiveLeaks We're gonna need you to respond. Are you on 1.8 and what server jar are you using?

**Comment by morg-mov** [comment]
I have the same issue. I am using the latest stable version (1.15.2) and running the latest version of spigot.

**Comment by MaxieDF** [comment]
@CyberFlameGO I forgot about this thread lol. I was on the wrong jar :P 
@IWantToScamBait You gotta use 1.8

**Comment by CyberFlameGO** [comment]
It's all good. Glad you found a fix.

**Comment by CyberFlameGO** [comment]
@HeathLoganCampbell Maybe close this issue?
