### ISSUE TITLE
Using MinecraftBut only on a specific world

### ISSUE THREAD

**Issue by MitzaBobitza** [HeathLoganCampbell/MinecraftBut#4]
Hey, i want to use MinecraftBut only on a specific multiverse world. is that possible?

**Comment by HeathLoganCampbell** [comment]
Just added a command to allow you to change the world the program is ran on. 
`/MinecraftBut worldChange <WorldName>` (The world must  be already loaded)

Note, We will not be supporting the plugin running on multiple worlds at the same time as it's out of the scope of need for the common youtuber

**Comment by MitzaBobitza** [comment]
i ran the comand /MinecraftBut worldChange MinecraftBut (thats how the world is called) but nothing happened. any fix?

**Comment by MitzaBobitza** [comment]
nevermind, it worked. thanks!
