### ISSUE TITLE
World border problem

### ISSUE THREAD

**Issue by MitzaBobitza** [HeathLoganCampbell/MinecraftBut#5]
I need help. i setted up MinecraftBut to run on a specific world named "MinecraftBut" by using the command /minecraftbut worldchange MinecraftBut and it worked, but if i restart my server the world border comes back to the main world and all the players die because "they suffocate in a wall". How can i fix that?

**Comment by MitzaBobitza** [comment]
Also i setted the lava is rising thing to start from 8 and i enabled lava is rising and my server has HUGE LAG. i use a good paid host so its not because of my server. when i enabled lava is rising the first time the lava came from the top but the server didnt lagged. please fix it.

**Comment by MitzaBobitza** [comment]
The lag is solved. Tho it might come again if i enable LavaIsRising again.

**Comment by MitzaBobitza** [comment]
The lag thing is solved but the command /minecraftbut worldchange didnt work. the lava is rising in my main world, not on my second world. also the command /minecraftbut scenario TheLavaRises LavaStartLevel 8 didnt work aswell. the lava came from the top of the map even after i typed the command. also dont forget the main problem i posted this issue for.

**Comment by OliveSheep** [comment]
The lava rises seemed to work for me.

**Comment by HeathLoganCampbell** [comment]
I'll look into the issue sometime later today, 
Is the lag client side, or server side.
If server side, I have ran the plugin on a $10 server and it worked fine from [MCProHosting](https://mcprohosting.com/order?aff=81875)
if client side, not much you can do besides get a better computer

You can shrink the boarder to have less lava spawn area
