### ISSUE TITLE
Downloading

### ISSUE THREAD

**Issue by tjplayzreal** [HeathLoganCampbell/MinecraftBut#7]
idk how to download any help is appreciated ! 👍

**Comment by HeathLoganCampbell** [comment]
"I do not know how to download. I added it to my mods folder and downloaded Forge 1.8 and 1.14 yet both didn't work. I have no entire clue how to download."

So this is a plugin for spigot 1.8  & 1.14, which is a server mod not a client side one.
I personally would suggest going a server from [MCProHosting](https://mcprohosting.com/order?aff=81875)
