### ISSUE TITLE
Scenario Help Issue

### ISSUE THREAD

**Issue by Postman67** [HeathLoganCampbell/MinecraftBut#9]
Whenever I execute _/minecraftbut s thewaterrises help_ nothing shows up.

**Comment by HeathLoganCampbell** [comment]
Capitalising matters, normally I just use tab for the correct word
"thewaterrises" => "TheWaterRises"

It's not a fully  developed plugin hence why it's not posted on spigot, so there is a few no user friendly features in  order to save time on my end
